Adding check if conffile is set before checking for existence

diff --git a/lib/hsn2/init-functions-java b/lib/hsn2/init-functions-java
--- a/lib/hsn2/init-functions-java
+++ b/lib/hsn2/init-functions-java
@@ -35,11 +35,13 @@ prepare() {
 }
 
 load_config() {
-	if [ -f $CONFFILE ]; then
-		. $CONFFILE
-	else
-		echo "Missing configuration file: $CONFFILE"
-		exit 1
+	if [ -n $CONFFILE ]; then
+		if [ -f $CONFFILE ]; then
+			. $CONFFILE
+		else
+			echo "Missing configuration file: $CONFFILE"
+			exit 1
+		fi
 	fi
 }
 
